version: '3'

services:
  house-system-frontend:
    build:
      context: .
      dockerfile: dockerfile
      network: host
    image: hewo233/house-system-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped